### ISSUE TITLE
Any plans for a release this weekend?

### ISSUE THREAD

**Issue by toranb** [felt/geo_postgis#159]
Huge fan of the work you've done here :) and I see on main that the latest commit is "prepare for release". I've upgrade to elixir 1.15.2 and noticed I had to turn on warnings in the short term because of the current stable release so I was curious if you might have time this weekend to release the fix I see already out.

Thanks again for all that you do to maintain this library!

**Comment by s3cur3** [comment]
I realize this issue is quite old, but v3.4.4 is out now with Elixir 1.15 compatibility (though see the notes about this in the [changelog](https://github.com/felt/geo_postgis/blob/master/CHANGELOG.md)). 😄
